### ISSUE TITLE
Review explanations Improvement

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/Darkly#20]
## Todo

- [x] BONUS-xss-breach-on-filename-file-upload
- [x] bruteforce-sign-in-form
- [x] directory-traversal-breach
- [x] htpasswd_admin_authentication_breach
- [x] i_am_admin_cookie_breach
- [x] mocking_referer_and_user_agent_curl_breach
- [x] php_script_as_jpg_metadata_file_upload_breach
- [x] query_param_driving_redirection
- [x] scraping_hidden_directory
- [x] search_images_sql_injection
- [x] sql_injection_members_table
- [x] ~~unknown_security_issue_on_recover_page~~ -> modify_value_form_fields_from_client
- [x] unprotected_select_value_on_survey_page
- [x] xss_on_feedbacks_page_breach
- [x] xss_page_nsa_image

**Comment by prastoin** [comment]
See https://github.com/AdonisEnProvence/Darkly/pull/21

**Comment by prastoin** [comment]
see #25
