### ISSUE TITLE
Final checks before closing the project for validation

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/Darkly#36]
## Todo

- [ ] Push to the Vogsphere the LAST version of the project
- [ ] Add a screenshot to the README
- [ ] Ensure all flag files end with a newline

**Comment by prastoin** [comment]
project has been validated
